# 把 PR 构建的页面推送到 Netlify
# 由于涉及 secrets，所以不能直接在 build.yml 中配置
name: Upload Preview

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Atifact
        run: gh --repo $GITHUB_REPOSITORY run download ${{github.event.workflow_run.id }} --name sites --dir sites
        env:
          GH_TOKEN: ${{ github.token }}

      - run: echo "PR_NUMBER=$(cat sites/pr_number)" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm

      - name: Install netlify-cli
        run: npm install -g netlify-cli

      - name: Upload Deploy
        run: netlify deploy --dir=sites --alias="pr-$PR_NUMBER"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PREVIEW_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PREVIEW_SITE_ID }}

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- preview comment -->'

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ env.PR_NUMBER }}
          body: |
            preview url: <https://pr-${{ env.PR_NUMBER }}--bangumi-next.netlify.app>
            <!-- preview comment -->
          edit-mode: replace
