# 把 PR 构建的页面推送到 Netlify
# 由于涉及 secrets，所以不能直接在 build.yml 中配置
name: Upload Preview (build)

on:
  workflow_run:
    workflows: ["Build", "Storybook Build"]
    types:
      - completed

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - echo '${{ toJSON(github) }}'

  upload-pr:
    strategy:
      max-parallel: 1
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Atifact
        run: gh --repo $GITHUB_REPOSITORY run download ${{github.event.workflow_run.id }} --name sites --dir sites
        env:
          GH_TOKEN: ${{ github.token }}

      - run: echo "PR_NUMBER=$(cat sites/pr_number)" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - run: echo "CLI_VER=$(npm show netlify-cli version)" >> $GITHUB_ENV

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ env.CLI_VER }}

      - name: Install netlify-cli
        run: npm install -g 'netlify-cli@${{ env.CLI_VER }}'

      - name: Upload Deploy
        run: netlify deploy --dir=sites --alias="pr-$PR_NUMBER"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PREVIEW_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PREVIEW_SITE_ID }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: "github-actions[bot]"
          body-includes: "<!-- build preview comment -->"

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ env.PR_NUMBER }}
          body: |
            preview url: <https://pr-${{ env.PR_NUMBER }}--bangumi-next.netlify.app>
            <!-- build preview comment -->
          edit-mode: replace

  upload-master:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'push' && 
      github.event.workflow_run.head_branch == 'master' && 
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download Atifact
        run: gh --repo $GITHUB_REPOSITORY run download ${{github.event.workflow_run.id }} --name sites --dir sites
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - run: echo "CLI_VER=$(npm show netlify-cli version)" >> $GITHUB_ENV

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ env.CLI_VER }}

      - name: Install netlify-cli
        run: npm install -g 'netlify-cli@${{ env.CLI_VER }}'

      - name: Upload Deploy
        run: netlify deploy --dir=sites --alias="master"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PREVIEW_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PREVIEW_SITE_ID }}
