name: Upload Preview (storybook)

on:
  workflow_run:
    workflows: ["Storybook Build"]
    types:
      - completed

jobs:
  upload-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download Atifact
        run: gh --repo $GITHUB_REPOSITORY run download ${{github.event.workflow_run.id }} --name storybook --dir storybook
        env:
          GH_TOKEN: ${{ github.token }}

      - run: echo "PR_NUMBER=$(cat storybook/pr_number)" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - run: echo "CLI_VER=$(npm show netlify-cli version)" >> $GITHUB_ENV

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ env.CLI_VER }}

      - name: Install netlify-cli
        run: npm install -g 'netlify-cli@${{ env.CLI_VER }}'

      - name: Upload Deploy
        run: netlify deploy --dir=storybook --alias="pr-$PR_NUMBER-storybook"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PREVIEW_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PREVIEW_SITE_ID }}

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: "github-actions[bot]"
          body-includes: "<!-- storybook preview comment -->"

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ env.PR_NUMBER }}
          body: |
            storybook preview url: <https://pr-${{ env.PR_NUMBER }}-storybook--bangumi-next.netlify.app>
            <!-- storybook preview comment -->
          edit-mode: replace

  upload-master:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'push' && 
      github.event.workflow_run.head_branch == 'master' && 
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download Atifact
        run: gh --repo $GITHUB_REPOSITORY run download ${{github.event.workflow_run.id }} --name storybook --dir storybook
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - run: echo "CLI_VER=$(npm show netlify-cli version)" >> $GITHUB_ENV

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ env.CLI_VER }}

      - name: Install netlify-cli
        run: npm install -g 'netlify-cli@${{ env.CLI_VER }}'

      - name: Upload Deploy
        run: netlify deploy --dir=storybook --alias="master-storybook"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PREVIEW_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PREVIEW_SITE_ID }}
